FROM openjdk:8-jdk-slim AS builder
WORKDIR /app

RUN apt-get update && apt-get install -y maven

COPY pom.xml .
COPY src ./src

RUN mvn clean package

FROM openjdk:8-jre-slim as runner
WORKDIR /app

COPY --from=builder /app/target/clean-architecture-0.0.1-SNAPSHOT.war .

EXPOSE 9090
CMD java -XX:+UseContainerSupport -Xmx512m -Dserver.port=9090 -jar clean-architecture-0.0.1-SNAPSHOT.war
